spring:
  rabbitmq:
    host: 101.132.151.4
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    # 这个配置存在后，才可以在监听器ConsumerListener写入参数Channel
    listener:
      simple:
        acknowledge-mode: manual  #开启手动ack
        prefetch: 10              # 每次获取多少条消息
    publisher-confirm-type: correlated  # 异步回调的方式
    publisher-returns: true  # 开启return机制

rabbitmq:
  exchange: "boot-exchange"
  queue: "boot-queue"
  routing: "*.black.*"