server:
  port: 8090
#============== kafka ===================
kafka:
  consumer:
#    zookeeper.connect: 172.22.124.60:2181
    servers: 172.22.124.60:9092,172.22.124.60:9094,172.22.124.60:9096
    enable.auto.commit: true
    session.timeout: 6000
    auto.commit.interval: 100
    auto.offset.reset: latest
    topic: test
    group.id: test
    concurrency: 1
  producer:
    servers: 172.22.124.60:9092,172.22.124.60:9094,172.22.124.60:9096
    retries: 0
    batch.size: 4096
    linger: 1
    buffer.memory: 40960